// challenges.ts

export interface Challenge {
  id: string;
  name: string;
  description: string;
  target: number;
  type: "boba" | "sessions" | "clicks" | "bps";
  completed: boolean;
  reward: number;
}

export const initialChallenges: Challenge[] = [
  {
    id: "rookie",
    name: "Rookie Brewer",
    description: "Brew 100 total boba",
    target: 100,
    type: "boba",
    completed: false,
    reward: 50,
  },
  {
    id: "focused",
    name: "Focused Mind",
    description: "Complete 5 focus sessions",
    target: 5,
    type: "sessions",
    completed: false,
    reward: 100,
  },
  {
    id: "clicker",
    name: "Fast Fingers",
    description: "Click 200 times",
    target: 200,
    type: "clicks",
    completed: false,
    reward: 75,
  },
  {
    id: "passive",
    name: "Passive Income",
    description: "Reach 10 boba per second",
    target: 10,
    type: "bps",
    completed: false,
    reward: 250,
  },
  {
    id: "master",
    name: "Boba Master",
    description: "Brew 1000 total boba",
    target: 1000,
    type: "boba",
    completed: false,
    reward: 500,
  },
  {
    id: "apprentice",
    name: "Boba Apprentice",
    description: "Brew 500 total boba",
    target: 500,
    type: "boba",
    completed: false,
    reward: 250,
  },
  {
    id: "grinder",
    name: "Session Grinder",
    description: "Complete 10 focus sessions",
    target: 10,
    type: "sessions",
    completed: false,
    reward: 150,
  },
  {
    id: "click-mania",
    name: "Click Mania",
    description: "Click 500 times",
    target: 500,
    type: "clicks",
    completed: false,
    reward: 200,
  },
  {
    id: "flow-state",
    name: "Flow State",
    description: "Complete 20 focus sessions",
    target: 20,
    type: "sessions",
    completed: false,
    reward: 400,
  },
  {
    id: "speedster",
    name: "Speedster",
    description: "Click 1000 times",
    target: 1000,
    type: "clicks",
    completed: false,
    reward: 350,
  },
  {
    id: "tycoon",
    name: "Boba Tycoon",
    description: "Reach 25 boba per second",
    target: 25,
    type: "bps",
    completed: false,
    reward: 750,
  },
  {
    id: "zen",
    name: "Zen Master",
    description: "Complete 50 focus sessions",
    target: 50,
    type: "sessions",
    completed: false,
    reward: 1000,
  },
  {
    id: "billionaire",
    name: "Billionaire Brewer",
    description: "Brew 10,000 total boba",
    target: 10000,
    type: "boba",
    completed: false,
    reward: 2000,
  },
  {
    id: "click-god",
    name: "Click God",
    description: "Click 5000 times",
    target: 5000,
    type: "clicks",
    completed: false,
    reward: 1500,
  },
  {
    id: "auto-clicker",
    name: "Auto Clicker",
    description: "Reach 50 boba per second",
    target: 50,
    type: "bps",
    completed: false,
    reward: 1500,
  },
  {
    id: "determined",
    name: "Determined Worker",
    description: "Complete 75 focus sessions",
    target: 75,
    type: "sessions",
    completed: false,
    reward: 2000,
  },
  {
    id: "infinite-clicks",
    name: "Infinite Clicks",
    description: "Click 10,000 times",
    target: 10000,
    type: "clicks",
    completed: false,
    reward: 2500,
  },
  {
    id: "legend",
    name: "Boba Legend",
    description: "Brew 50,000 total boba",
    target: 50000,
    type: "boba",
    completed: false,
    reward: 5000,
  },
  {
    id: "click-machine",
    name: "Click Machine",
    description: "Click 25,000 times",
    target: 25000,
    type: "clicks",
    completed: false,
    reward: 6000,
  },
  {
    id: "unstoppable",
    name: "Unstoppable",
    description: "Complete 100 focus sessions",
    target: 100,
    type: "sessions",
    completed: false,
    reward: 3000,
  },
  {
    id: "empire",
    name: "Boba Empire",
    description: "Reach 100 boba per second",
    target: 100,
    type: "bps",
    completed: false,
    reward: 5000,
  },
  {
    id: "max-boba",
    name: "Max Boba",
    description: "Brew 100,000 total boba",
    target: 100000,
    type: "boba",
    completed: false,
    reward: 10000,
  },
  {
    id: "click-universe",
    name: "Click Universe",
    description: "Click 50,000 times",
    target: 50000,
    type: "clicks",
    completed: false,
    reward: 12000,
  },
  {
    id: "boba-god",
    name: "Boba God",
    description: "Brew 500,000 total boba",
    target: 500000,
    type: "boba",
    completed: false,
    reward: 50000,
  },
];
